// Spanish translations. The key is the exact English text used in tr('...').
// Anything missing here simply shows in English.
const es = {
  " and ": " y ",
  " · {rate}% sales tax": " · {rate}% de impuesto sobre ventas",
  "/month": "/mes",
  "1 estimator login": "1 acceso de estimador",
  "12 Elm St, Springfield, MA": "Calle Olmo 12, Springfield, MA",
  "A service with no price yet shows as \"Priced separately — TBD\" on a quote until you set a rate under Pricing.": "Un servicio sin precio aparece como \"Se cotiza por separado — por definir\" en la cotización hasta que le pongas una tarifa en Precios.",
  "Access, slope, irrigation, anything the office should know…": "Acceso, pendiente, riego, cualquier cosa que la oficina deba saber…",
  "Add": "Agregar",
  "Add a note (optional)": "Agrega una nota (opcional)",
  "Add photos": "Agregar fotos",
  "Alex Rivera": "Alex Rivera",
  "Already have an account? Sign in": "¿Ya tienes una cuenta? Inicia sesión",
  "Anything not listed above…": "Cualquier cosa que no esté en la lista…",
  "Appearance": "Apariencia",
  "Area per service": "Área por servicio",
  "Ask the account owner to upgrade the plan.": "Pídele al dueño de la cuenta que mejore el plan.",
  "At least 6 characters": "Al menos 6 caracteres",
  "Back": "Atrás",
  "Back to sign in": "Volver a iniciar sesión",
  "Billing is not connected yet, so nothing is charged and the change applies right away.": "La facturación aún no está conectada, así que no se cobra nada y el cambio se aplica de inmediato.",
  "Brand color": "Color de marca",
  "Building PDF…": "Creando PDF…",
  "Business & branding": "Negocio y marca",
  "Business address": "Dirección del negocio",
  "Business name": "Nombre del negocio",
  "Business profile & branding": "Perfil del negocio y marca",
  "Business settings": "Ajustes del negocio",
  "Camera or library": "Cámara o biblioteca",
  "Cancel": "Cancelar",
  "Change": "Cambiar",
  "Check your email": "Revisa tu correo",
  "Confirm": "Confirmar",
  "Contact email": "Correo de contacto",
  "Contact name": "Nombre de contacto",
  "Contact phone": "Teléfono de contacto",
  "Contact us": "Contáctanos",
  "Copied": "Copiado",
  "Copy link": "Copiar enlace",
  "Copy this invite link:": "Copia este enlace de invitación:",
  "Cost breakdown": "Desglose de costos",
  "Could not build the PDF. Try again.": "No se pudo crear el PDF. Inténtalo de nuevo.",
  "Could not cancel that invite.": "No se pudo cancelar esa invitación.",
  "Could not change your plan. Try again.": "No se pudo cambiar tu plan. Inténtalo de nuevo.",
  "Could not create that invite.": "No se pudo crear esa invitación.",
  "Could not delete that quote.": "No se pudo eliminar esa cotización.",
  "Could not load saved quotes.": "No se pudieron cargar las cotizaciones guardadas.",
  "Could not load your team.": "No se pudo cargar tu equipo.",
  "Could not remove that person.": "No se pudo quitar a esa persona.",
  "Could not save your business info. Check your connection and try again.": "No se pudo guardar la información de tu negocio. Revisa tu conexión e inténtalo de nuevo.",
  "Could not save your details.": "No se pudieron guardar tus datos.",
  "Could not update that quote.": "No se pudo actualizar esa cotización.",
  "Count": "Cantidad",
  "Create account": "Crear cuenta",
  "Create invite link": "Crear enlace de invitación",
  "Create your account": "Crea tu cuenta",
  "Creating…": "Creando…",
  "Crew members": "Integrantes de la cuadrilla",
  "Cubic yards": "Yardas cúbicas",
  "Current": "Actual",
  "Current plan": "Plan actual",
  "Customer name": "Nombre del cliente",
  "Customer quote": "Cotización para el cliente",
  "Danger zone": "Zona de peligro",
  "Dark": "Oscuro",
  "Day-rate gear the crew uses on jobs.": "Equipo con tarifa diaria que usa la cuadrilla en los trabajos.",
  "Delete": "Eliminar",
  "Delete all my data": "Eliminar todos mis datos",
  "Delete my business data": "Eliminar los datos de mi negocio",
  "Delete the quote for {name}?": "¿Eliminar la cotización de {name}?",
  "Disposal": "Desecho",
  "Download PDF": "Descargar PDF",
  "Dump fee": "Tarifa de descarga",
  "Dump loads": "Cargas al vertedero",
  "Each": "Por unidad",
  "Edit": "Editar",
  "Email": "Correo electrónico",
  "Email failed to send.": "No se pudo enviar el correo.",
  "Enterprise": "Empresarial",
  "Equipment": "Equipo",
  "Equipment fuel": "Combustible del equipo",
  "Equipment fuel cost": "Costo de combustible del equipo",
  "Equipment name": "Nombre del equipo",
  "Equipment used": "Equipo usado",
  "Estimator": "Estimador",
  "Every quote your team builds is saved here automatically.": "Cada cotización que arma tu equipo se guarda aquí automáticamente.",
  "General settings": "Ajustes generales",
  "Get started": "Comenzar",
  "Hourly rate, mileage, dump fees": "Tarifa por hora, millaje, tarifas de descarga",
  "How your prices are built from your costs.": "Cómo se arman tus precios a partir de tus costos.",
  "Invite an estimator": "Invitar a un estimador",
  "Invite estimators by email, remove people": "Invita estimadores por correo, quita personas",
  "Invite estimators to quote under your company. They use your prices and see every saved quote.": "Invita estimadores para cotizar a nombre de tu empresa. Usan tus precios y ven todas las cotizaciones guardadas.",
  "Job Details": "Detalles del trabajo",
  "Job notes": "Notas del trabajo",
  "Labor": "Mano de obra",
  "Labor hours": "Horas de trabajo",
  "Labor rate": "Tarifa de mano de obra",
  "Labor, travel & disposal": "Mano de obra, viaje y desecho",
  "Language": "Idioma",
  "Leave": "Salir",
  "Leave blank to use the property square footage above.": "Déjalo en blanco para usar los pies cuadrados de la propiedad de arriba.",
  "Light": "Claro",
  "Linear feet": "Pies lineales",
  "Linear footage": "Pies lineales",
  "Loading...": "Cargando...",
  "Loading…": "Cargando…",
  "Logo": "Logotipo",
  "Lost": "Perdida",
  "Manage plan": "Administrar plan",
  "Margins, minimums & tax": "Márgenes, mínimos e impuestos",
  "Material needed": "Material necesario",
  "Materials & pricing": "Materiales y precios",
  "Measurements drive the material cost.": "Las medidas determinan el costo del material.",
  "Mileage rate": "Tarifa por milla",
  "Minimum job charge": "Cargo mínimo por trabajo",
  "More than 500 quotes a month, more than 10 estimators, or several locations.": "Más de 500 cotizaciones al mes, más de 10 estimadores o varias sedes.",
  "Most popular": "Más popular",
  "My name & phone": "Mi nombre y teléfono",
  "Name": "Nombre",
  "Name (optional)": "Nombre (opcional)",
  "Name, contact info, logo, brand color": "Nombre, datos de contacto, logotipo, color de marca",
  "New here? Create an account": "¿Eres nuevo? Crea una cuenta",
  "New service name": "Nombre del nuevo servicio",
  "Next": "Siguiente",
  "No address": "Sin dirección",
  "No saved quotes yet. Build one on the New quote tab and it shows up here.": "Aún no hay cotizaciones guardadas. Arma una en la pestaña Nueva cotización y aparecerá aquí.",
  "No services selected.": "No hay servicios seleccionados.",
  "Not included in totals": "No incluido en los totales",
  "Note": "Nota",
  "Notes": "Notas",
  "Nothing matches that.": "Nada coincide con eso.",
  "One login for your whole business — use it on any device.": "Un solo acceso para todo tu negocio: úsalo en cualquier dispositivo.",
  "Only the owner can change the plan.": "Solo el dueño puede cambiar el plan.",
  "Optional. Shows as its own line on the PDF": "Opcional. Aparece como una línea aparte en el PDF",
  "Other equipment / notes": "Otro equipo / notas",
  "Owner": "Dueño",
  "Password": "Contraseña",
  "Per hour, per crew member": "Por hora, por integrante",
  "Permanently removes your account's business info": "Elimina permanentemente la información de negocio de tu cuenta",
  "Phone number": "Número de teléfono",
  "Pick your trades. We add starter services and equipment you can edit later.": "Elige tus oficios. Agregamos servicios y equipo iniciales que puedes editar después.",
  "Please wait...": "Espera un momento...",
  "Plowing and shoveling scale with depth; every snow service multiplies by the number of pushes. Quoting a seasonal contract? Enter the visits you expect.": "El despeje con pala y arado depende de la profundidad; cada servicio de nieve se multiplica por el número de pasadas. ¿Cotizas un contrato de temporada? Anota las visitas que esperas.",
  "Priced on each quote": "Se define en cada cotización",
  "Priced separately — TBD": "Se cotiza por separado — por definir",
  "Profit built into every quote": "Ganancia incluida en cada cotización",
  "Profit margin ({pct}% of quote)": "Margen de ganancia ({pct}% de la cotización)",
  "Property Info": "Datos de la propiedad",
  "Property address": "Dirección de la propiedad",
  "Property square footage": "Pies cuadrados de la propiedad",
  "Pushes / visits": "Pasadas / visitas",
  "Quote status": "Estado de la cotización",
  "Quote summary": "Resumen de la cotización",
  "Quotes price themselves as your crew fills in the job on site.": "Las cotizaciones se calculan solas mientras tu cuadrilla llena el trabajo en sitio.",
  "Raised to the {amount} minimum job charge.": "Se subió al cargo mínimo por trabajo de {amount}.",
  "Rates, units and notes for each service": "Tarifas, unidades y notas de cada servicio",
  "Remove": "Quitar",
  "Remove {who} from {team}?": "¿Quitar a {who} de {team}?",
  "Resets {date}": "Se reinicia el {date}",
  "Review quote": "Revisar cotización",
  "Riverside Landscaping": "Jardinería Riverside",
  "Round trip to the job": "Ida y vuelta al trabajo",
  "Running quote": "Cotización en curso",
  "Sales tax": "Impuesto sobre ventas",
  "Save": "Guardar",
  "Save changes": "Guardar cambios",
  "Saved for reference, not applied to quotes yet": "Guardado como referencia, aún no se aplica a las cotizaciones",
  "Saved quotes": "Cotizaciones guardadas",
  "Saved to your company's quotes": "Guardada en las cotizaciones de tu empresa",
  "Saved.": "Guardado.",
  "Saving...": "Guardando...",
  "Saving…": "Guardando…",
  "Search customer, address or teammate": "Buscar cliente, dirección o compañero",
  "Sections": "Secciones",
  "See who is on your team and update your name": "Mira quién está en tu equipo y actualiza tu nombre",
  "Send a finished quote straight to your office with one tap.": "Envía una cotización terminada directo a tu oficina con un toque.",
  "Send quote": "Enviar cotización",
  "Send quotes to": "Enviar cotizaciones a",
  "Send this link to": "Envía este enlace a",
  "Send to {name}": "Enviar a {name}",
  "Sending…": "Enviando…",
  "Sent to {name}": "Enviada a {name}",
  "Service name": "Nombre del servicio",
  "Service or material name": "Nombre del servicio o material",
  "Services Needed": "Servicios necesarios",
  "Services you offer": "Servicios que ofreces",
  "Set up my own business instead": "Mejor configurar mi propio negocio",
  "Set your own materials, equipment and labor rates once — reuse them on every job.": "Configura una vez tus materiales, equipo y tarifas de mano de obra, y reutilízalos en cada trabajo.",
  "Settings": "Ajustes",
  "Shown as \"prepared by\" on the quotes you send.": "Aparece como \"preparado por\" en las cotizaciones que envías.",
  "Shown as 'prepared by' on your quotes": "Aparece como \"preparado por\" en tus cotizaciones",
  "Shown at the top of every quote you send.": "Aparece en la parte de arriba de cada cotización que envías.",
  "Sign In": "Acceso",
  "Sign Out": "Cerrar sesión",
  "Sign in": "Iniciar sesión",
  "Sign in to your Pricr account.": "Inicia sesión en tu cuenta de Pricr.",
  "Sign out": "Cerrar sesión",
  "Sign out of Pricr on this device?": "¿Cerrar sesión de Pricr en este dispositivo?",
  "Signed in as {email}": "Sesión iniciada como {email}",
  "Signed in as {email}. If this is the wrong account, sign out and use the email your admin invited.": "Sesión iniciada como {email}. Si es la cuenta equivocada, cierra sesión y usa el correo al que te invitó tu administrador.",
  "Site notes": "Notas del sitio",
  "Site photos": "Fotos del sitio",
  "Smallest quote you'll send": "La cotización más pequeña que enviarás",
  "Snow conditions": "Condiciones de nieve",
  "Snowfall depth": "Profundidad de nevada",
  "Something went wrong. Try again.": "Algo salió mal. Inténtalo de nuevo.",
  "Square feet": "Pies cuadrados",
  "Start new estimate": "Empezar nueva cotización",
  "Start quoting": "Empezar a cotizar",
  "Switch to {plan}": "Cambiar a {plan}",
  "Switch to {plan} for {price} a month?": "¿Cambiar a {plan} por {price} al mes?",
  "TBD": "Por definir",
  "TBD (priced separately)": "Por definir (se cotiza por separado)",
  "Tap everything this job covers. You can change it later.": "Toca todo lo que incluye este trabajo. Lo puedes cambiar después.",
  "Target margin": "Margen objetivo",
  "Target margin {pct}%": "Margen objetivo {pct}%",
  "Team": "Equipo",
  "Team & invites": "Equipo e invitaciones",
  "Team settings": "Ajustes del equipo",
  "Teammate": "Compañero",
  "That invite didn't work": "Esa invitación no funcionó",
  "Theme": "Tema",
  "They sign up with the email you enter here. You'll get a link to text or email them. It works once and expires in 14 days.": "Se registran con el correo que escribas aquí. Recibirás un enlace para enviárselo por mensaje o correo. Funciona una sola vez y vence en 14 días.",
  "They'll take it from here.": "Ellos se encargarán a partir de aquí.",
  "This estimate": "Esta cotización",
  "This permanently deletes your business info, contacts, materials, equipment and rates from Pricr's servers, then signs you out. This can't be undone.": "Esto elimina permanentemente la información de tu negocio, contactos, materiales, equipo y tarifas de los servidores de Pricr, y luego cierra tu sesión. No se puede deshacer.",
  "This permanently deletes your business info, services, equipment, rates and team from Pricr, then signs you out. It can't be undone.": "Esto elimina permanentemente la información de tu negocio, servicios, equipo, tarifas y equipo de trabajo de Pricr, y luego cierra tu sesión. No se puede deshacer.",
  "This quote couldn't be saved to your company's list. It will retry when you come back to this screen. You can still send it or download the PDF.": "No se pudo guardar esta cotización en la lista de tu empresa. Se reintentará cuando vuelvas a esta pantalla. Aún puedes enviarla o descargar el PDF.",
  "This quote was saved before reopening was supported.": "Esta cotización se guardó antes de que se pudiera volver a abrir.",
  "This quote wasn't saved because you've used every quote on your plan this month. You can still send it or download the PDF.": "Esta cotización no se guardó porque ya usaste todas las cotizaciones de tu plan este mes. Aún puedes enviarla o descargar el PDF.",
  "Total cost": "Costo total",
  "Transfer station, per load": "Estación de transferencia, por carga",
  "Travel": "Viaje",
  "Trip minimum": "Mínimo por viaje",
  "Try again": "Reintentar",
  "Turn a site walk into an accurate, on-brand quote in minutes — right from your phone.": "Convierte un recorrido del sitio en una cotización precisa y con tu marca en minutos, directo desde tu teléfono.",
  "Type every service your company provides. They show up as tabs when you build a quote. Set what you charge for each one under Pricing.": "Escribe cada servicio que ofrece tu empresa. Aparecen como pestañas cuando armas una cotización. Define cuánto cobras por cada uno en Precios.",
  "Unnamed customer": "Cliente sin nombre",
  "Up to {n} quotes a month": "Hasta {n} cotizaciones al mes",
  "Upgrade plan": "Mejorar plan",
  "Upgrade to {plan}": "Mejorar a {plan}",
  "Upload": "Subir",
  "Uploading...": "Subiendo...",
  "Waiting": "En espera",
  "Waiting to join": "Esperando para unirse",
  "We sent a confirmation link to {email}. Click it, then come back here and sign in.": "Enviamos un enlace de confirmación a {email}. Ábrelo, luego regresa aquí e inicia sesión.",
  "Welcome back": "Bienvenido de nuevo",
  "Welcome to Pricr": "Bienvenido a Pricr",
  "What the job costs {name} to run.": "Lo que le cuesta a {name} hacer el trabajo.",
  "What you charge for each service. Pick the unit, set the rate, and add a note if it helps.": "Lo que cobras por cada servicio. Elige la unidad, pon la tarifa y agrega una nota si ayuda.",
  "What you charge for time, driving and dump runs.": "Lo que cobras por tiempo, manejo y viajes al vertedero.",
  "What you do": "A qué te dedicas",
  "Which crew": "Qué cuadrilla",
  "Which tab": "Qué pestaña",
  "Who and where. Everything else builds off this.": "Quién y dónde. Todo lo demás parte de esto.",
  "Who gets each completed quote by email.": "Quién recibe por correo cada cotización terminada.",
  "Who's using Pricr on this device.": "Quién usa Pricr en este dispositivo.",
  "Whoever's on-site today": "Quien esté en el sitio hoy",
  "Won": "Ganada",
  "Yes, delete everything": "Sí, eliminar todo",
  "Yes, reset everything": "Sí, restablecer todo",
  "You": "Tú",
  "You have already used {n} quotes this month.": "Ya usaste {n} cotizaciones este mes.",
  "You have {n} people on your team. This plan allows {max}.": "Tienes {n} personas en tu equipo. Este plan permite {max}.",
  "You joined {name}. Quotes use the company's prices.": "Te uniste a {name}. Las cotizaciones usan los precios de la empresa.",
  "You're on {name}'s team. You quote with the company's prices.": "Estás en el equipo de {name}. Cotizas con los precios de la empresa.",
  "You've been invited to join a team. Create your account (or sign in) with the email address you were invited at.": "Te invitaron a unirte a un equipo. Crea tu cuenta (o inicia sesión) con el correo al que te invitaron.",
  "You've used all {max} quotes on your {plan} plan this month. Quotes you already started are safe.": "Ya usaste las {max} cotizaciones de tu plan {plan} este mes. Las cotizaciones que ya empezaste están a salvo.",
  "You've used every quote on your plan this month. Upgrade to keep quoting.": "Ya usaste todas las cotizaciones de tu plan este mes. Mejora tu plan para seguir cotizando.",
  "Your business": "Tu negocio",
  "Your details": "Tus datos",
  "Your email": "Tu correo",
  "Your name": "Tu nombre",
  "Your own pricing, branded PDFs, photos and snow quoting": "Tus propios precios, PDF con tu marca, fotos y cotización de nieve",
  "Your phone": "Tu teléfono",
  "Your team": "Tu equipo",
  "Your {plan} plan includes {n} estimator logins. Upgrade your plan to add more people.": "Tu plan {plan} incluye {n} accesos de estimador. Mejora tu plan para agregar más personas.",
  "crew": "cuadrilla",
  "day": "día",
  "e.g. Brush clearing": "p. ej. Limpieza de maleza",
  "expires": "vence el",
  "required": "obligatorio",
  "the team": "el equipo",
  "this company": "esta empresa",
  "this customer": "este cliente",
  "{customer} — {price} quote was emailed to {email}.": "{customer}: la cotización de {price} se envió a {email}.",
  "{h} hrs × {c} crew × {r}/hr": "{h} h × {c} personas × {r}/h",
  "{mi} mi × 2 (round trip) × {r}/mi": "{mi} mi × 2 (ida y vuelta) × {r}/mi",
  "{name} will take it from here.": "{name} se encargará a partir de aquí.",
  "{n} estimator logins": "{n} accesos de estimador",
  "{plan} · {used} of {max} quotes used this month": "{plan} · {used} de {max} cotizaciones usadas este mes",
  "{used} of {max} quotes used this month": "{used} de {max} cotizaciones usadas este mes",
  "Property": "Propiedad",
  "Services": "Servicios",
  "Quote": "Cotización",
  "New quote": "Nueva cotización",
  "Quotes": "Cotizaciones",
  "Starter": "Inicial",
  "Pro": "Pro",
  "Business": "Negocio",
  "{n} service selected": "{n} servicio seleccionado",
  "{n} services selected": "{n} servicios seleccionados",
  "{n} photo": "{n} foto",
  "{n} photos": "{n} fotos",
  "{n} day": "{n} día",
  "{n} days": "{n} días",
  "{n} load": "{n} carga",
  "{n} loads": "{n} cargas",
  "Excludes {items} — {office} prices those separately.": "Excluye {items}: {office} los cotiza por separado.",
  "Excludes {items} — {office} prices that separately.": "Excluye {items}: {office} lo cotiza por separado.",
  "{n} service · type in everything you do": "{n} servicio · escribe todo lo que haces",
  "{n} services · type in everything you do": "{n} servicios · escribe todo lo que haces",
  "{n} item · day rates": "{n} artículo · tarifas diarias",
  "{n} items · day rates": "{n} artículos · tarifas diarias",
  "All": "Todas",
  "Draft": "Borrador",
  "Sent": "Enviada",
  "Pricing": "Precios",
  "Rates": "Tarifas",
  "Margins": "Márgenes",
  "Terms": "Términos",
  "Service pricing": "Precios de servicios",
  "Materials": "Materiales",
  "{n} material · what each one costs you": "{n} material · lo que te cuesta cada uno",
  "{n} materials · what each one costs you": "{n} materiales · lo que te cuesta cada uno",
  "Rates, margins & employees": "Tarifas, márgenes y empleados",
  "{n} employee": "{n} empleado",
  "{n} employees": "{n} empleados",
  "Terms & payment": "Términos y pago",
  "Custom terms on every quote": "Términos personalizados en cada cotización",
  "Payment terms and conditions on every quote": "Términos de pago y condiciones en cada cotización",
  "Employees": "Empleados",
  "Employee name": "Nombre del empleado",
  "+ Add employee": "+ Agregar empleado",
  "Hourly": "Por hora",
  "Daily": "Por día",
  "Weekly": "Por semana",
  "Yearly salary": "Salario anual",
  "Add each person and what you pay them. Daily is figured on 8 hours, weekly on 40 and salary on 2,080 hours a year. Pick them on a quote to cost labor from their actual wages.": "Agrega a cada persona y lo que le pagas. El pago diario se calcula con 8 horas, el semanal con 40 y el salario con 2,080 horas al año. Elígelos en una cotización para calcular la mano de obra con sus sueldos reales.",
  "Who's on this job": "Quién está en este trabajo",
  "Pick your employees to cost labor from their actual wages. Leave blank to use the number of crew members and your labor rate.": "Elige a tus empleados para calcular la mano de obra con sus sueldos reales. Déjalo en blanco para usar el número de miembros del equipo y tu tarifa de mano de obra.",
  "{n} selected below": "{n} elegidos abajo",
  "Your own materials and what each one costs you, like the different stones you install. Pick them on a quote and enter how much the job needs.": "Tus propios materiales y lo que te cuesta cada uno, como los distintos tipos de piedra que instalas. Elígelos en una cotización e ingresa cuánto necesita el trabajo.",
  "Material name, e.g. Bluestone": "Nombre del material, p. ej. Piedra azul",
  "+ Add material": "+ Agregar material",
  "No materials yet. Add the materials you buy and what each one costs.": "Aún no hay materiales. Agrega los materiales que compras y lo que cuesta cada uno.",
  "Cubic yards": "Yardas cúbicas",
  "Tons": "Toneladas",
  "Pallets": "Tarimas",
  "Bags": "Bolsas",
  "Enter how much of each material this job needs.": "Ingresa cuánto de cada material necesita este trabajo.",
  "Total drive distance (miles)": "Distancia total de manejo (millas)",
  "{mi} mi × {r}/mi": "{mi} mi × {r}/mi",
  "Per mile driven": "Por milla manejada",
  "Terms and conditions": "Términos y condiciones",
  "Payment terms, deposits, warranty and anything else you want printed on every quote.": "Términos de pago, depósitos, garantía y todo lo que quieras imprimir en cada cotización.",
  "Add example wording": "Agregar texto de ejemplo",
  "Contact Pricr to raise your quote limit.": "Comunícate con Pricr para aumentar tu límite de cotizaciones."
}

export default es
